name: flutter_langdetect_example
description: An example console application using the flutter_langdetect package.
version: 1.0.0

environment:
  flutter: ^3.24.4
  sdk: ^3.5.0

dependencies:
  flutter_langdetect:
    path: ../
